# Usa una imagen oficial de Node.js como base
FROM node:16

WORKDIR /var/www/html

# Ajustar la ruta según la ubicación de tu package.json
COPY cursito-app/package.json cursito-app/package-lock.json ./

RUN npm install

COPY cursito-app ./

CMD ["npm", "run", "dev"]
