version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "82:80"
    volumes:
      - ./cursito-app:/var/www/html
    depends_on:
      - database

  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_database
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3307:3306"